server:
  port: 8188
  servlet:
    context-path: /web-passport
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/products
    username: passportpguser
    password: pgpwd4passport
  flyway:
    user: passportpguser
    password: pgpwd4passport
    url: jdbc:postgresql://postgres:5432/products
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect